### ISSUE TITLE
Fields for Doctor Specialisation

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care#1150]
```yaml
Fields to be added to the user model:
  doctor_qualification:                 Mandatory CharField
  doctor_experience_commenced_on:       Mandatory DateField # to store month and year only
  doctor_medical_council_registration:  Mandatory CharField

  # doctor_specialisation will be built as an extension over UserSkills in a later PR.
```

Related to https://github.com/coronasafe/care_fe/issues/4501

> When registering a doctor user type (https://care.coronasafe.in/users/add) the following additional fields to be added to the form
> 
>     * Specialisation- dropdown with search function. The list of specialities is available at https://docs.google.com/spreadsheets/d/1lCBF2hhmlYV3paPP3xIep6tPHmzTefdD67w-eaKql7I/edit?usp=sharing
> 
>     * Qualification- short text field- mandatory field
> 
>     * Years of experience- drop-down (0, 1-2, 3-5, 5-7, 7-10, more than 10) years- mandatory field
> 
>     * Medical council registration No. (short field for numeric values accepting max 10 digits)- mandatory field
> 
>     * [ ]  Make all the input visible in the user list
> 
>     * [ ]  Make qualification and specialty appear against the name in the doctor  connect panel (https://care.coronasafe.in/facility/a31e6a24-0146-4043-b295-3a6c2fe7e095/patient/86db5dde-ffdb-4473-9eab-3e6b2088d7d6/consultation/de8455fa-3d11-49e3-9dc2-1aaec616379b)
