### ISSUE TITLE
Patient Consultation: Route to Facility

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care#1671]
As part of https://github.com/coronasafe/care_fe/issues/6280:

## Consultation Status → Route to Facility

- [ ] Add field `route_to_facility` (choices: `OUTPATIENT`, `INTER_FACILITY_TRANSFER`, `INTRA_FACILITY_TRANSFER`)
- [ ] Route to Facility should be a required field.
- [ ] Deprecate old field: `consultation_status` to `deprecated_consultation_status`
- [ ] Map `consultation_status` to `route_to_facility` as follows:

```yaml
Brought Dead:                    Outpatient/Emergency Room
Transferred from Ward:           Internal Transfer within the facility
Transferred from ICU:            Internal Transfer within the facility
Referred from another hospital:  Referred from another facility
Outpatient:                      Outpatient/Emergency Room
```

### Related places to be updated

- [ ] Update CSV Export
- [ ] Update Discharge Summary

### Fields for "Referred from another facility"

- [ ] Add field: `referred_from_facility`, `referred_from_external` facility (required)
- [ ] Add field: `referred_by_external_facility` user (textfield, non-mandatory)
- [ ] Add field: `icu_admission_date` (non-mandatory)

### Fields for "Internal Transfer within the Facility"
- [ ] Add field: `transferred_from_location` location field (required)
- [ ] Add field: `icu_admission_date` (non-mandatory)
