### ISSUE TITLE
Add persistance to localstack image

### ISSUE THREAD

**Issue by sainak** [coronasafe/care#1944]
https://docs.localstack.cloud/user-guide/state-management/persistence/
```yml
    image: localstack/localstack
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?}
      - PERSISTENCE=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
```
